### ISSUE TITLE
v2.5 Class APIRequestCreateAdVideo#setVideoFileChunk(String) parameter type error

### ISSUE THREAD

**Issue by wangguanquan** [facebook/facebook-java-ads-sdk#10]
As title. The method's parameter type should be java.io.File not java.lang.String. As my understand is not correct, please correct me, thanks.

**Comment by JiamingFB** [comment]
Hi wangguanquan,

This is a valid bug and we'll fix it.
To unblock, you can call setParam("video_file_chunk", file) instead.

**Comment by wangguanquan** [comment]
Thanks.
