### ISSUE TITLE
Question : Can I use ad rule engine with Facebook SDK 2.9?

### ISSUE THREAD

**Issue by pillowwork** [facebook/facebook-java-ads-sdk#100]
Question : Can I use ad rule engine with Facebook SDK 2.9?

I do not know where to post a question, so I leave a question here.

Our team is developing using Facebook SDK 2.9 version.

And I want to use Ad Rule Engine through SDK.

Is Ad Rule Engine available in the current version of SDK?

**Comment by guxufb** [comment]
SDK only support publically available features.  Ad Rule Engine is still in beta and thus it will not be avaliable in SDKs.  Please do check back when the feature becomes public and you should be able to use in SDK at that time.
