### ISSUE TITLE
Get campaign, get adsets of multiple campaign, and report batch.

### ISSUE THREAD

**Issue by pillowwork** [facebook/facebook-java-ads-sdk#103]
I get campaign, ad sets, and report information through sdk.

It shows a reasonable pace when fetching campaign information.

When you fetch AdSet information for multiple campaigns (about 150), it shows the speed that the website can not use.

In order to retrieve spending and impressions for campaigns and AdSets, the use of batches in the SDK to load reports also shows a speed that is not available on the website.

Is there a way to improve speed?

Maybe I'm using the SDK incorrectly?

I will leave the code I wrote. (I think it's almost the same as your example.)

*get campaigns
        APIContext apiContext = new APIContext(accessToken).enableDebug(false);
        AdAccount account = new AdAccount(adaccountid, apiContext);
        APINodeList<Campaign> campaigns = account.getCampaigns().requestAllFields().execute();

        while (campaigns != null) {
            /* codes */
            campaigns = campaigns.nextPage();
        }

*get adsets of multiple campaign
        for (Campaign campaign : campaignList) {
            for(AdSet adset : campaign.getAdSets().requestAllFields().execute()) {
                /* codes */
            }
        }

*batch report (campaign)
        BatchRequest batch = new BatchRequest(apiContext);
        for (CustomCampaign campaign : customCampaignList) {
            new Campaign(campaignId, apiContext).getInsightsAsync()
                    .setTimeRanges("[{'since':'" + startDate + "', 'until':'" + endDate + "'}]")
                    .requestField("campaign_id").requestField("spend").requestField("impressions")
                    .requestField("actions")
                    .addToBatch(batch, campaignId);
        }

        List<APIResponse> responses = batch.execute();

        for (APIResponse response : responses) {
                AdReportRun report = AdReportRun.loadJSON(response.getRawResponse(), apiContext);
                while ( ( report.fetch().getFieldAsyncPercentCompletion() != 100 ) || ( report.getFieldAsyncStatus().toUpperCase().indexOf( COMPLETE_STATUS ) < 0 ) ) {
                    //report.getFieldAsyncPercentCompletion();
                    //Thread.sleep(5000);
                }
                APINodeList<AdsInsights> insights = report.getInsights().execute();
        }

*bat report (adset of multiple campaign)
        BatchRequest batch = new BatchRequest(apiContext);

        for (AdSet adSet : adSetList) {
            String adSetId = adSet.getId();
            adSet.getInsightsAsync()
                    .setTimeRanges("[{'since':'" + startDate + "', 'until':'" + endDate + "'}]")
                    .requestField("adset_id").requestField("spend").requestField("campaign_id")
                    .addToBatch(batch, adSetId);
        }

        List<APIResponse> responses = batch.execute();

        for (APIResponse response : responses) {
                AdReportRun report = AdReportRun.loadJSON(response.getRawResponse(), apiContext);
                while ( ( report.fetch().getFieldAsyncPercentCompletion() != 100 ) || ( report.getFieldAsyncStatus().toUpperCase().indexOf( COMPLETE_STATUS ) < 0 ) ) {
                    //report.getFieldAsyncPercentCompletion();
                    //Thread.sleep(5000);
                }
                APINodeList<AdsInsights> insights = report.getInsights().execute();
        }

**Comment by AndreyBatkovich** [comment]
Can you show how did you get campaign, ad sets? I have a little confusion with id's and tokens.

**Comment by AndreyBatkovich** [comment]
please

**Comment by pillowwork** [comment]
The source code is above.
I think the problem I was asking was not the SDK, but the problem of other parts of our project.
I will end this question.
