### ISSUE TITLE
When getting leads , can I filter by created_time atribute?

### ISSUE THREAD

**Issue by FBrusquetti** [facebook/facebook-java-ads-sdk#106]
Im trying to get leads , but i  just want those that have a creation time greater than a especific date-time value.
there is a similar example in php here:
![github](https://user-images.githubusercontent.com/17968329/29194773-2617a986-7df9-11e7-9f22-f1963b4af1d9.PNG)

I have tried it passing a map object to the execute method like this but it did not work,its still getting all the leads:

LeadgenForm form = new LeadgenForm(FORM_ID, context);
Map<String, Object> params = new HashMap<String, Object>();
		 params.put("field", "time_created");
		 params.put("operator", "GREATER_THAN");
		 params.put("value", <Long number with unix timestamp format>);

APINodeList<Lead> respuestasJson = form.getLeads().execute(params);

**Comment by cloudxu** [comment]
Thanks for reaching out. For API question, we are encourage developers to post questions to https://www.facebook.com/groups/pmdcommunity/

Thanks,
Cloud
