### ISSUE TITLE
AdsInsights Object is Missing Fields. 

### ISSUE THREAD

**Issue by bdiesenhaus** [facebook/facebook-java-ads-sdk#11]
Reference https://developers.facebook.com/docs/marketing-api/reference/ads-insights. The AdInsights Object is missing the estimated_ad_recall_rate and objective fields

**Comment by JiamingFB** [comment]
Hi bdiesenhaus, just to unblock, you can read the raw json value of the object. In this way you can access the field if it is returned from server but missing in the object.
`JsonParser parser = new JsonParser();`
`JsonObject rawJson = parser.parse(ad.getRawValue()).getAsJsonObject();`
`System.out.println(rawJson.get("adset_id"));`

We'll update the sdk soon to add the new api response fields.

**Comment by bdiesenhaus** [comment]
I found two additional fields that are missing on the AdInsights object, cps and clicks:

https://developers.facebook.com/docs/marketing-api/reference/ads-insights

cpc -The average cost per click for these ads, calculated as the amount spent divided by the number of clicks received.

clicks - The total number of clicks on your ad. Depending on what you're promoting, this can include Page likes, event responses or app installs.

**Comment by JiamingFB** [comment]
Hi bdiesenhaus,
These fields will be included in next release (~1 week). They were added after last sdk release and that was why they were not included.

**Comment by JiamingFB** [comment]
These fields are added in the new release.
