### ISSUE TITLE
'age' and 'gender' erroneously removed from AdsInsights for 2.10?

### ISSUE THREAD

**Issue by eyebe** [facebook/facebook-java-ads-sdk#113]
In the 2.10 release, the `age` and `gender` fields were removed from the `com.facebook.ads.sdk.AdsInsights` class.

If you request insights with a breakdown by age and gender, those fields appear in the response (see example below).  But how are those values retrievable using the classes in this library?  

**Request**:
`curl -G -d "breakdowns=age,gender" -d "fields=impressions" -d "access_token=<ACCESS_TOKEN>" 
"https://graph.facebook.com/<API_VERSION>/<AD_CAMPAIGN_ID>/insights"`
or
`AdAccount adAccount = ...;
AdReportRun report = adAccount.getInsightsAsync().setBreakdowns( EnumBreakdowns.VALUE_AGE, EnumBreakdowns.VALUE_GENDER ).setFields("impressions").execute().head();
// wait for data
APINodeList<AdsInsights> adsInsights = report.getInsights().execute();
`

**Response** (JSON):
`{
  "data": [
    {
      "impressions": "4",
      "date_start": "2016-03-05",
      "date_stop": "2016-04-01",
      "age": "13-17",
      "gender": "female"
    },
    ...,
    {
      "impressions": "4314",
      "date_start": "2016-03-05",
      "date_stop": "2016-04-01",
      "age": "25-34",
      "gender": "male"
    }
  ],
  "paging": {
    "cursors": {
      "before": "MAZDZD",
      "after": "MgZDZD"
    }
  }
}`

Example request and data from [developers.facebook.com](https://developers.facebook.com/docs/marketing-api/insights/breakdowns)

**Comment by bfalese-navent** [comment]
I'm also having this issue.

**Comment by alejobs** [comment]
Please take a look at #116

**Comment by lintaocui** [comment]
Those fields getter are removed by design. They are also removed in ads api documentation.

**Comment by bfalese-navent** [comment]
what does it mean it was removed by design? 

is not better to support the complete facebook API?
