### ISSUE TITLE
autocomplete search

### ISSUE THREAD

**Issue by sang-d** [facebook/facebook-java-ads-sdk#12]
Hi,
Does the SDK support autocomplete search for targeting objects such as (location, locale..) 
I was trying to use APIRequestGetTargetingSearch class, but couldn't execute on AdAccount Node.

Basically I'm trying to build query like this: search?q=un&type=adgeolocation
Please let me know if I misunderstanding about this functionality.
Thanks,

**Comment by JiamingFB** [comment]
Hi DINHXUANSANG,

Right now the SDK doesn't have a dedicated class to support search, but you can create an ad-hoc APIRequest to achieve that:

      Map<String, Object> params = new HashMap<>();
      params.put("q", "un");
      params.put("type", "adgeolocation");
      System.out.println(new APIRequest<APINode>(context, "", "search", "GET").execute(params));

**Comment by DINHXUANSANG** [comment]
thanks JiamingFB, it's helpful!

**Comment by ignatda** [comment]
Hi! Is adgeolocation type still not available for a search by facebook-java-business-sdk?
