### ISSUE TITLE
Getting incomplete Ads analytics data

### ISSUE THREAD

**Issue by manssa01** [facebook/facebook-java-ads-sdk#120]
Hello,

I am using the following code to get insights metrics, but I get only impressions and spends, other metrics have the value null:

package ea.dan.facebook;

import com.facebook.ads.sdk.APIContext;
import com.facebook.ads.sdk.APIException;
import com.facebook.ads.sdk.APINodeList;
import com.facebook.ads.sdk.APIRequest;
import com.facebook.ads.sdk.Ad;
import com.facebook.ads.sdk.AdAccount;
import com.facebook.ads.sdk.AdSet;
import com.facebook.ads.sdk.AdsActionStats;
import com.facebook.ads.sdk.AdsInsights;
import com.facebook.ads.sdk.Campaign;
import com.restfb.Connection;
import com.restfb.json.JsonObject;
import com.restfb.types.Insight;
import java.util.Iterator;
import java.util.List;

/**
 *
 * @author manssa01
 */

     public static void main(String[] args) throws APIException {
        APIContext("********************************************************************************************");      
 try {
      APIRequest<AdAccount> request = new APIRequest<>(context, "me", "/adaccounts", "GET", AdAccount.getParser());
      APINodeList<AdAccount> accounts = (APINodeList<AdAccount>)(request.execute());
      for (AdAccount account : accounts) {
            APINodeList<Campaign> campaigns = new AdAccount( account.getId(), context).getCampaigns().requestAllFields()
        .execute();
            for (Campaign campaign : campaigns) {
                 APINodeList<AdSet> adSets = new Campaign( campaign.getId(), context).getAdSets().requestAllFields()
          .execute();
           for (AdSet adset : adSets) {

                 APINodeList<Ad> ads = new AdSet( adset.getId(), context).getAds().requestAllFields()
        .execute();
                 
                 for (Ad ad:ads) {
                      APINodeList<AdsInsights> adInsights = new Ad(ad.getId(), context).getInsights().requestField("inline_link_clicks")
        .execute();
                       for (AdsInsights adInsight : adInsights) {
                           System.out.println(adInsight);
                           
                       }
                       }
                      
                 }
               }  
               }
    } catch (Exception e) {
      e.printStackTrace();
    }
    } 
    
}

I don't know why I can not show the number of clicks....

I look forward to hearing from you.

Thanks and best regards,
Repro URL:
https://developers.facebook.com/tools/explorer/133162044075487/?session_id=128832081091352

**Comment by mayur-raval** [comment]
You could try getting individual fields until this is fixed. Thats what worked for me. requestAllFields() gave me nothing, so I tried requestField(<fieldName>) for all required fields and that worked.

**Comment by manssa01** [comment]
Hello,
Thanks for your feedback, I tried it also, I didn't get better result.

Best regards,

**Comment by mayur-raval** [comment]
Here is what worked for me. However I fetched insights for campaign rather than adset.
1. Async request:
```
APIRequestGetInsightsAsync insightsAsync = new com.facebook.ads.sdk.Campaign(campaignId, context).getInsightsAsync();
AdReportRun report = insightsAsync
				.requestField("objective")
		                .requestField("reach")
		                .requestField("impressions")
		                .requestField("clicks")
		                .requestField("outbound_clicks")
		                .requestField("cpc")
		                .requestField("cost_per_action_type")
		                .requestField("cost_per_unique_click")
		                .requestField("spend")
		                .requestField("cpm")
		                .execute()
		                .head();
while (report.fetch().getFieldAsyncPercentCompletion() != 100) {
			        try {
						Thread.sleep(3000);
					} catch (InterruptedException e) {
						LOGGER.error("Thread interuppted from sleep while waiting for async insights");
					}
			    }
		        
		        APINodeList<AdsInsights> insights = report.getInsights().execute();
```

2. Direct request:
`APINodeList<AdsInsights> insights = new com.facebook.ads.sdk.Campaign(campaignId, context).getInsights().requestField("spend").execute();`

**Comment by manssa01** [comment]
I tried it again,

It seems better now.
Many thanks

**Comment by ablejohnson1** [comment]
The following issue is related to this one
https://github.com/facebook/facebook-java-ads-sdk/issues/116
