### ISSUE TITLE
Breakdown fields not available in adinsight class in 2.10 and above

### ISSUE THREAD

**Issue by confessin** [facebook/facebook-java-ads-sdk#122]
I recently migrated from 2.9 and one of my insight api calls include hourly reports. VALUE_HOURLY_STATS_AGGREGATED_BY_ADVERTISER_TIME_ZONE

The result in api which is a List of AdsInsight class does not contain any getter to get the breakdown field in AdsInsight. 

In my case in 2.9 I was doing adInsight.getFieldHourlyStatsAggregatedByAdvertiserTimeZone() but in 2.10/2.11 no such getter exists.

Please help

**Comment by pavelbr** [comment]
You should implement the same workaround as in https://github.com/facebook/facebook-java-ads-sdk/issues/116

**Comment by lintaocui** [comment]
Those fields getter are removed by design. They are also removed in ads api documentation.
