### ISSUE TITLE
Add optional retry for transient errors. 

### ISSUE THREAD

**Issue by bdiesenhaus** [facebook/facebook-java-ads-sdk#14]
I get a decent amount of transient errors while calling the Facebook api. Immediate retries of the same request work. It would be nice to add retry support into the sdk, possibly in APIRequest.callInternal(). The response has the is_transient field in it, if this is true it would be nice if the sdks retried instead of all calling clients to have to catch the APIException, check if it it is transient and then retry everywhere a request is made. Making this optional by adding a boolean (retry) with the number of retry attempts to the APIContext would allow for users to turn retries on or off.

Exception from sdks: 
com.facebook.ads.sdk.APIException: {"error":{"message":"An unexpected error has occurred. Please retry your request later.","type":"OAuthException","is_transient":true,"code":2,"fbtrace_id":"DAbvR5wiN2d"}}

**Comment by bdiesenhaus** [comment]
After looking into this further the check should be on the code 2  - API ServiceTemporary issue due to downtime - retry the operation after waiting not on the is_transient field.

**Comment by JiamingFB** [comment]
Hi bdiesenhaus, in next version we'll provide interface to override sendGet, sendPost, and sendDelete in APIRequest, where you can easily customize and add auto-retry logic.

We don't have plan to add the retry in SDK, because it could be risky to silently retry requests, especially for POST, which could potentially create duplicated ads.

**Comment by bdiesenhaus** [comment]
@JiamingFB , thanks any idea on timing of the next version?

**Comment by JiamingFB** [comment]
The next SDK version will come with the next API version, which is expected to be in April.

**Comment by JiamingFB** [comment]
New version was just released.
Please refer to the NetworkCustomisation example for handling retries for request failures. Thanks!
