### ISSUE TITLE
Publish to maven central

### ISSUE THREAD

**Issue by 0cd** [facebook/facebook-java-ads-sdk#18]
Better than just making jars available for download

**Comment by JiamingFB** [comment]
Thanks for the suggestion!
We do have plan to add the SDK to maven central. We just need a little more efforts on documentation and beta testing before doing that.

**Comment by redoc123** [comment]
Hi JiaminFB, 

Do you have any update on this? Could you add the beta/pre-beta version with appropriate tag in maven repo? 

~B

**Comment by nemccarthy** [comment]
+1

**Comment by mkuznetsov** [comment]
hi, I don't find SDK on maven central. Do still plan to publish it?

**Comment by igorschut** [comment]
+1

**Comment by paroos** [comment]
+1

**Comment by paroos** [comment]
@0cd @JiamingFB @redoc123 @nemccarthy @mkuznetsov @igorschut You can use JitPack.

1. Add JitPack to your pom.xml

```
	<repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories>
```

2. Declare the dependency
```

	<dependency>
	    <groupId>com.github.facebook</groupId>
	    <artifactId>facebook-java-ads-sdk</artifactId>
	    <version>v0.2.0</version>
	</dependency>
```

**Comment by JiamingFB** [comment]
Hi All,

This SDK is now published on Maven Central:
<groupId>com.facebook.ads.sdk</groupId>
<artifactId>facebook-java-ads-sdk</artifactId>
<version>0.4.0</version>

Please let me know if you have any difficulty in adding it to you dependency.

Thanks,
Jiaming

**Comment by 0cd** [comment]
When can we expect ver 2.9.0 in maven? Only 0.4.0 is present

https://mvnrepository.com/artifact/com.facebook.ads.sdk/facebook-java-ads-sdk

**Comment by lamkrodrigues** [comment]
Guys, download .jar is legacy past, please upgrade to Maven! ;)

**Comment by omerkenshoo** [comment]
Maven central is missing 2.11.0
Is it maintained?
