### ISSUE TITLE
Ad Accounts Audience Insights Query

### ISSUE THREAD

**Issue by 0cd** [facebook/facebook-java-ads-sdk#19]
https://developers.facebook.com/docs/marketing-api/reference/ad-account/audience_insights_query

Are are there plans to support this API?

**Comment by JiamingFB** [comment]
Hi 0cd,

This feature is not completely open to public yet, so SDK will not include it now. We'll add it when it's open.

**Comment by SindhuKancharla** [comment]
https://developers.facebook.com/docs/graph-api/reference/audience-insights-query/

Is this supported yet?

**Comment by rovanalfarry** [comment]
Hello @JiamingFB we have a standar access facebook api/app, it still can't access for Audience Insight Query?
