### ISSUE TITLE
Cannot get tabs from user/account

### ISSUE THREAD

**Issue by sang-d** [facebook/facebook-java-ads-sdk#21]
Hi,
In the previous version, I could get pages'  tabs from ConnectionObject node.
In 2.6, I couldn't get this object from account (page) node, as it throws exception:
" Requires either an app access token, or a page access token for this Page"

Is that intended feature? I'm able to get promotable_posts from this node, so just want to double check.
Thanks.

 
        User user = new User(fbUserId, context);        

        APINodeList<APINode> accountList = user.getAccounts()

                                .requestField("id")

                                .requestField("name")

                                .requestField("promotable_posts")

                                //.requestField("tabs") //require page accesstoken

                                .requestField("picture").execute();

**Comment by JiamingFB** [comment]
Hi sang-d,

In the [page doc](https://developers.facebook.com/docs/graph-api/reference/page/tabs/), it is said that "All of these methods require a Page Access Token." I think the error is intended.

You can refer to [this page](https://developers.facebook.com/docs/pages/access-tokens) for generating page access token. It's just a simple call to /{page-id}?fields=access_token
