### ISSUE TITLE
error create Link Ad Preview

### ISSUE THREAD

**Issue by sang-d** [facebook/facebook-java-ads-sdk#22]
Hi,

I'm not sure it's right place to post this question, it seems happening to python SDK as well.
For me I'm using this java-sdk to develop my app. So I just want to post here, in case any one can take a look and advise.

I'm trying to get ad-preview for a link ad based on 
https://developers.facebook.com/docs/marketing-api/reference/ad-creative-link-data/

"The preview iframe received doesn't render creative but showing: 
Using unsupported field in object_story_spec: The field force_single_link is not supported in the field link_data of object_story_spec."

Can you advise what need to be done for this field: force_single_link?
I've tried different cases: remove this field from object_story_spec, set true or false, but still having same error.

```

AdCreative creative = new AdCreative();
AdCreativeObjectStorySpec objStorySpec = new AdCreativeObjectStorySpec();
AdCreativeLinkData linkData = new AdCreativeLinkData();
linkData.setFieldLink(obj.getString("link_url"));
//linkData.setFieldForceSingleLink(false);
linkData.setFieldImageHash(obj.getString("image_hash"));

objStorySpec.setFieldLinkData(linkData);
objStorySpec.setFieldPageId(obj.getString("page_id"));
creative.setFieldObjectStorySpec(objStorySpec);
```

Thanks
Sang

**Comment by JiamingFB** [comment]
Hello Sang,

This looks like a backend issue with ad preview. I see a similar bug reported even without using SDK. I'll keep you posted on the status. Thanks!

**Comment by sang-d** [comment]
this is fixed at https://developers.facebook.com/bugs/243280216062166/
