### ISSUE TITLE
Fetching businesses leads to NPE

### ISSUE THREAD

**Issue by hkroger** [facebook/facebook-java-ads-sdk#24]
Business.java, row 149, inside parseResponse():

```
JsonObject paging = obj.get("paging").getAsJsonObject().get("cursors").getAsJsonObject();
```

This causes a null pointer exception in API when trying to fetch all businesses of a user like this:

```
APINodeList<Business> x = (APINodeList) ((APINodeList) (new APIRequest(context, "", "/me/businesses", "GET", Business.getParser())).execute());
```

Reason is that the API endpoint in question doesn't return cursors.

**Comment by guxufb** [comment]
This issue should have been fixed.
