### ISSUE TITLE
How to get audience_size of specific audience name ?

### ISSUE THREAD

**Issue by huutuan** [facebook/facebook-java-ads-sdk#25]
I have a set of audiences name, but not audience id. 
How can I get the size of each audience, audience type and audience id. 
Example: I have exactly name of audience: "Design Engineer". I want to get audience type is "work_positions", audience id is "109542932398298" and audience size is "105197"

Thanks !

**Comment by JiamingFB** [comment]
Hi huutuan, I think you just need a GET request to AdAccount.getCustomAudiences() and then set filter with name equals the desired name.
