### ISSUE TITLE
Audience Insights Query - Access Token/Required Scope

### ISSUE THREAD

**Issue by RossS1982** [facebook/facebook-java-ads-sdk#26]
https://developers.facebook.com/docs/graph-api/reference/audience-insights-query/

How do I access this via my app? Would I have to request ads_management? read_insights? ads_read?

**Comment by JiamingFB** [comment]
Please see https://developers.facebook.com/docs/marketing-api/reference/ad-account/audience_insights_query/

**Comment by RamaAnumalla** [comment]
How to use facebooks javascript sdk api to pull audience insights demographics ?? Please any one know how to implement help me
