### ISSUE TITLE
Error Handling Documentation

### ISSUE THREAD

**Issue by nirfeldman** [facebook/facebook-java-ads-sdk#3]
There is no documentation regarding Error Handling.
Suggest you add some.

@christinelu FYI

**Comment by xiaotchen** [comment]
Thanks for reporting the Ads API SDK bug! Could you please provide more details on what type of error handling documentation you would like to see? Thanks again!

**Comment by xiaotchen** [comment]
I'll just close the issue for now. Please feel free to reopen the issue if there's anything we could improve here. Thanks!
