### ISSUE TITLE
Method Account.getInsights() fail 

### ISSUE THREAD

**Issue by root1984** [facebook/facebook-java-ads-sdk#31]
Error Message: Object with ID 'act_5620100000000975' does not exist

I think you need remove "act_" in request.

**Comment by JiamingFB** [comment]
Hi root1984,

'act_' prefix is required for all requests on AdAccount object. The error message means that you don't have access to the corresponding ad account. Could you please double check?

**Comment by JiamingFB** [comment]
Assuming it's fixed.

Feel free to re-open if the issue still exists and please provide more details.
