### ISSUE TITLE
AdSet.requestAllFields() doesn't return name

### ISSUE THREAD

**Issue by sang-d** [facebook/facebook-java-ads-sdk#34]
Hi,
It returns all other fields but not name. So probably it's a bug?

<img width="583" alt="screen shot 2016-07-02 at 12 25 02 pm" src="https://cloud.githubusercontent.com/assets/11723598/16538492/1f5e72f6-4050-11e6-8932-bcfe44517f2e.png">

Thanks,
Sang

**Comment by JiamingFB** [comment]
Hi Sang,

When I use requestAllFields, I do get 'name' field...

Could you please:
1. enable debug mode by: new APIContext(ACCESS_TOKEN, APP_SECRET).enableDebug(true)
2. check the output and find the request url. i) check if 'name' is in the 'fields' param, and ii) try to run it in API Explorer: https://developers.facebook.com/tools/explorer

If 'name' is in requested 'fields', and you get response without 'name' field, then it is an API bug and you can report on https://developers.facebook.com/bugs/

Thanks!

**Comment by guxuoss** [comment]
Assuming this issue has been resolved.
