### ISSUE TITLE
Reasons for supporting EnumOptimizationGoal 'Clicks' in AdSet

### ISSUE THREAD

**Issue by paroos** [facebook/facebook-java-ads-sdk#36]
Hi there

Why do you support OptimizationGoal 'Clicks' in AdSet (EnumOptimizationGoal)? This feature isn't supported by the facebook api since version 2.4.

@SerializedName("CLICKS")
VALUE_CLICKS("CLICKS")

If it's a failure, I will create a PR.

Thanks in advance.

Kind regards, Patrick

**Comment by JiamingFB** [comment]
Hi parros,

"CLICKS" is deprecated and we now use "LINK_CLICKS" or other goals instead. The value "CLICKS" is kept in the enum because some old AdSets still use "CLICKS" as optimization goal, and it will appear when you read the data for those AdSets.

**Comment by paroos** [comment]
Hi @JiamingFB 

Thanks for your quick answer. Now, I understand the reason.

Thanks. 

Patrick

**Comment by paroos** [comment]
Issue closed.
