### ISSUE TITLE
Saved audiences

### ISSUE THREAD

**Issue by markotron** [facebook/facebook-java-ads-sdk#37]
Hi. 

How do I load all the saved audiences? I managed to load custom audiences with `account.getCustomAudiences().requestField("name").execute();` but I don't get the saved audiences. 

I see that there is an endpoint for loading saved audiences by id: https://developers.facebook.com/docs/marketing-api/reference/saved-audience/

but how do I get the IDs? :)

Best, 
M

**Comment by JiamingFB** [comment]
Hi M,

Looks like there is no open api to get saved_audiences yet... You can get those from Ads Manager UI though. I'll check internally to see if there could be an endpoint for that.

Thanks!

**Comment by markotron** [comment]
Thanks, that would help a lot.

**Comment by JiamingFB** [comment]
act_xxx/saved_audiences should be public now.
