### ISSUE TITLE
The library depends on gson version 2.5: 

### ISSUE THREAD

**Issue by nirfeldman** [facebook/facebook-java-ads-sdk#4]
You should consider testing it with more versions - maybe 2 versions (so apps that use a different version of gson). For us it's not an issue.
Your pom should specify which versions are acceptable.
e.g.:
[2.4,2.5]

This is low priority from our end (since it does not collides) but might be an issue for an app that is using gson on different version then 2.5

**Comment by JiamingFB** [comment]
right now the sdk pom requires gson 2.5+, and default to 2.5 unless it has conflict with other dependencies.
