### ISSUE TITLE
BatchRequest size limit

### ISSUE THREAD

**Issue by lupuleti** [facebook/facebook-java-ads-sdk#40]
Hello,

Is there any chance that the 50 requests limit per batch could be increased ? 

Thank you !
Kind Regards !
Catalin

**Comment by JiamingFB** [comment]
Hi lupuleti,

Currently there is no way to go above the 50-request limit. The limit is enforced on server side and is primarily to prevent http request timeout and also prevent our backend from being overloaded.

You can probably use your client-side logic to split large batch into a few 50-request batches. I'm sorry if this causes complication in your code, but this seems to be the only way to do it right now.

Thanks!
