### ISSUE TITLE
AdCreativeLinkDataCallToActionValue is not utilized

### ISSUE THREAD

**Issue by 0cd** [facebook/facebook-java-ads-sdk#42]
When creating an AdCreative, passing an instance of AdCreativeLinkDataCallToActionValue to adCreativeLinkDataCallToAction.setFieldValue(..) doesn't  have an effect - those CTA parameters are not present in the resulting adCreative.

Instead, we are forced to use the form adCreativeLinkDataCallToAction.setFieldValue(String s), and pass in json in a string - only then do we see the correct CTA parameters on the resulting adCreative.

**Comment by guxuoss** [comment]
Thanks for reporting Ads API SDK bug!

Have you populate the instance of AdCreativeLinkDataCallToActionValue with couple of "setField..." calls like this:
```Java
AdCreativeLinkDataCallToActionValue value = new AdCreativeLinkDataCallToActionValue();
value.setFieldLinkTitle("This is Title")
  .setFieldLinkDescription("This is Description")
  .setFieldLink("http://link");
```

Please help us understand and debug your issues with more examples.

**Comment by 0cd** [comment]
This is how we are using it -

    adCreativeObjectStorySpec.setFieldVideoData(
        new AdCreativeVideoData()
            ..
            .setFieldCallToAction(
                new AdCreativeLinkDataCallToAction()
                    .setFieldType(..)
                    .setFieldValue(
                        new AdCreativeLinkDataCallToActionValue()
                            .setFieldLink(link)
                            .setFieldLinkCaption(caption)
                            .setFieldLinkDescription(description)
                            .setFieldLinkTitle(title)
                    )
            )
            ..
    )

then we set adCreativeObjectStorySpec on an APIRequestCreateAdCreative, to create the adCreative

**Comment by guxuoss** [comment]
We still cannot repo the issue from our side.  Can you check whether the Json string you are using is the same with what you set on AdCreativeLinkDataCallToActionValue.  The only possibility I can image is that some special characters cannot be correctly handled by our encoder but your own JSON serializer did a good job.  It would be great if you can also provide your JSON string to allow us repo.

If you are not confirmable to share, could you provide trace ids of your calls or ids of these creatives? We need some data to repo your issue.

**Comment by guxuoss** [comment]
Close this issue as we cannot repo.
