### ISSUE TITLE
Documentation for detailed targeting.

### ISSUE THREAD

**Issue by pushkarjajoria** [facebook/facebook-java-ads-sdk#43]
I was unable to find enums or documentation on targeting adverts on Facebook.
For eg: "setFieldGenders( )" takes a list of long as an arguments but its not clear which number corresponds to which gender, can you point me to a documentation which I can refer for these cases?

Thanks in advance.
Pushkar

**Comment by JiamingFB** [comment]
Hi pushkarjajoria,

Please refer to Facebook Marketing API docs:
https://developers.facebook.com/docs/marketing-api/targeting-specs/v2.7

For genders in targeting:
1=male
2=female.
Defaults to all.

Thanks!

**Comment by ruud17** [comment]
@JiamingFB what value to send in a case "defaults to all"?
