### ISSUE TITLE
duplicate ads, ad sets or campaigns in sdk

### ISSUE THREAD

**Issue by zhengzhiyuan** [facebook/facebook-java-ads-sdk#44]
hi
   Would like to know is there any way to I duplicate ads, ad sets or campaigns in sdk , similar to Power Editor.
   It will be very helpful.

**Comment by guxuoss** [comment]
We do not have this feature available in SDKs.  One way you can do is to pull objects with all fields but you need to forward the right fields to the creation calls.   But we do received similar ask from other developers and are actively working on it.
