### ISSUE TITLE
Put user limitation

### ISSUE THREAD

**Issue by violetkjs** [facebook/facebook-java-ads-sdk#46]
Hi 

i try to put 'madid'( Android advertising ID) to custom audience. 

and i want to know limitation of user's data.

if i had tried to put 30000 data,
 i got  {"error":{"code":1,"message":"An unknown error occurred","error_subcode":99}}

so could you let me know limitation of added user.

**Comment by cloudxu** [comment]
@violetkjs, Getting unknown error is not expected. I would encourage you to open a bug https://developers.facebook.com/bugs/ with all the information you have. It will be great if you can attach the full response (with fbtrace_id) to help us understand what happened.

**Comment by violetkjs** [comment]
@cloudxu Thanks for reply

i got information from your link. one user faced same problem. and i got some information.

Thanks
