### ISSUE TITLE
How to get Ads using facebook java SDK

### ISSUE THREAD

**Issue by bvgpon** [facebook/facebook-java-ads-sdk#49]
can you help me to get the ads of a campaign using the facebook java API.

and can u also provide a proper documentation for the facebook-java-ads-sdk.

**Comment by cloudxu** [comment]
@bvgpon, Please look at the sample code folders for example for example, this is the code to get all adsets from a campaign:

https://github.com/facebook/facebook-java-ads-sdk/blob/master/examples/BasicExample.java#L101

We are keep refining out documentation on developer.facebook.com. Java SDK is quite new, we are catching up.
