### ISSUE TITLE
Sample Code Not Working

### ISSUE THREAD

**Issue by MichaelCropper** [facebook/facebook-java-ads-sdk#50]
Sample code to create a campaign listed on the main Code page on Github, doesn't work. Sample code within the Examples folder for QuickStartExample, doesn't work. 

Does anyone have any working sample code to get this working?

**Comment by lintaocui** [comment]
Hi, Michael, Thanks for reporting the Ads API SDK bug.

We cannot repo what you have reported and need more information to investigate. Could you please provide the error information to help us moving forward?

Some tips:
1. Did you update your own accesstoken/app secret/adaccount id in ExampleConfig.java?

**Comment by lintaocui** [comment]
Close it. Let us know if you find the example not work for you.
