### ISSUE TITLE
how to get pagination for adhoc request

### ISSUE THREAD

**Issue by sang-d** [facebook/facebook-java-ads-sdk#51]
Hi team,
Just have a question, how does pagination work for cases like below:

```
    APIResponse res = new APIRequest<APINode>(context, "", "search", "GET").execute(params);
```

Please advise. 
Thanks,
Sang

**Comment by JiamingFB** [comment]
Hi @sang-d 

You can do something like the following. Basically you can cast the api response into a APINodeList<APINode>, and then do the pagination.

        APIRequest<Campaign> campaigns_request = new APIRequest<Campaign>(context, "act_" + account.getId(), "/campaigns", "GET", null, Campaign.getParser())
            .requestField("name");
        APINodeList<Campaign> campaigns = (APINodeList<Campaign>)(campaigns_request.execute());
        for (Campaign campaign : campaigns) {
          System.out.println("campaign: " + campaign);
        }
        campaigns = campaigns.nextPage();
        for (Campaign campaign : campaigns) {
            System.out.println("campaign: " + campaign);
        }
