### ISSUE TITLE
Uploading video caption file fails

### ISSUE THREAD

**Issue by kilink** [facebook/facebook-java-ads-sdk#55]
[Uploading of video captions](https://developers.facebook.com/docs/graph-api/reference/video/captions/#Creating) fails due to the way the default request executor [determines mime types](https://github.com/facebook/facebook-java-ads-sdk/blob/master/src/main/java/com/facebook/ads/sdk/APIRequest.java#L322-L329) based on file extension; it uses a fixed mapping that doesn't include ".srt", so the Facebook API endpoint rejects the request.

A more foolproof method would be to fall back to a default mimetype such as "application/octet-stream" when one can't be determined based on file extension. [Files.probeContentType](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#probeContentType-java.nio.file.Path-) could also be utilized to delegate to more sophisticated user supplied file type detectors such as Tika.

**Comment by daphyFB** [comment]
Hi, thanks for reporting the Ads API SDK bug! Since this will be addressed by https://github.com/facebook/facebook-java-ads-sdk/pull/56, I'll close this issue. Thanks a lot again!
