### ISSUE TITLE
Ajax error is not formatted correctly

### ISSUE THREAD

**Issue by sang-d** [facebook/facebook-java-ads-sdk#57]
Currently, ajax error message is:

responseText: "{"success":false, "code": 13, "message": "{"error":{"message":"Invalid parameter","type":"OAuthException","code":100,"error_data":{"blame_field_specs":[["daily_budget"]]},"error_subcode":1885272,"is_transient":false,"error_user_title":"Your Budget Is Too Low","error_user_msg":"The minimum budget for this ad set is $19.90.","fbtrace_id":"B8zThZN6jAv"}}"}"

Which cannot parse by JSON. 
The correct one should be: (removing the double quote around responseText.message

{"success":false, "code": 13, "message": {"error":{"message":"Invalid parameter","type":"OAuthException","code":100,"error_data":{"blame_field_specs":[["daily_budget"]]},"error_subcode":1885272,"is_transient":false,"error_user_title":"Your Budget Is Too Low","error_user_msg":"The minimum budget for this ad set is $19.90.","fbtrace_id":"B8zThZN6jAv"}}}

**Comment by guxuoss** [comment]
Thanks for the feedback.  I think this response is from API and not related to the SDK.  Could you please share your sample code to repo this issue?  Please remove any personal information from the sample, like access token and ad object ids.

**Comment by sang-d** [comment]
thanks guxuoss, pls close this ticket
