### ISSUE TITLE
java 1.7 support?

### ISSUE THREAD

**Issue by chrisptang** [facebook/facebook-java-ads-sdk#61]
Hi, it seems like current package only supports java 1.8+, while some of our exists projects are using 1.7 or older. It requires a lot of extra works to upgrade all our projects to java 1.8. Would you plan to support java1.7 in the future?

**Comment by locspin** [comment]
Seconded. Only supporting Java 1.8+ requires similar changes in our
ecosystem. We are manually calling the API until that is resolved, which is
a pain.

**Comment by chrisptang** [comment]
Hi @locspin 
I just build a jdk1.7 version: https://github.com/chrisptang/facebook-java-ads-sdk/tree/master/target

Main changes:

- Use org.apache.commons.lang.StringUtils.join instead of java8 String.join
- Fix this NullPointerException bug: https://github.com/facebook/facebook-java-ads-sdk/issues/60

Enjoy.

**Comment by lintaocui** [comment]
Hi @chrisptang @locspin , thank you for reporting the issue. Support Java 1.7 sounds reasonable, given there are already two asks for it. We are keeping this issue tracked.

**Comment by JiamingFB** [comment]
Java 7 is now supported in latest release

**Comment by chrisptang** [comment]
Sounds great.
