### ISSUE TITLE
How can I do to create and publish a new lead generation form?

### ISSUE THREAD

**Issue by stefanoerrani** [facebook/facebook-java-ads-sdk#62]
Good day.
There is a way in order to create a new lead generation form and publish it on facebook ads?
I've seen there there are some classes but I cannot found a connection with adcreative or ad classes.
Have you an example in order to make it?
Best regards.
Stefano Errani

**Comment by lintaocui** [comment]
@stefanoerrani thank you for reporting the issue, we will work on it and get back to you later.

**Comment by lintaocui** [comment]
Hi, @stefanoerrani Right now we don't support create/edit lead gen form using API. Only read is supported.
