### ISSUE TITLE
Get list of all available action_types

### ISSUE THREAD

**Issue by xardazz** [facebook/facebook-java-ads-sdk#64]
Is there any endpoint to get all possible values (including custom ones) for the field action_type?
For pixels I found that 
account_id/customconversions endpoint can be used (in that case the action_type will be "offsite_conversion.fb_pixel_" + custom_event_type)
But I couldn't find anything similar for custom conversion app events. Can you advice me somthing?

**Comment by xiaotchen** [comment]
Thanks for reporting the Ads API SDK issue! Unfortunately at this point I couldn't realize any endpoints for your needs. Would you mind also posting your question to "Facebook Marketing Developer Community" group (https://www.facebook.com/groups/pmdcommunity/)? Thank you and enjoy the rest of your day!
