### ISSUE TITLE
Fields of AdsInsights missing in v0.4.0

### ISSUE THREAD

**Issue by liu-shiyuan** [facebook/facebook-java-ads-sdk#66]
FieldGender
FieldAge
FieldCountry
FieldPlacement
FieldImpressionDevice
FieldProductId
FieldRegion

Fields above are missing, please add them to Object of AdsInsights,
or can you tell me how to get these insight fields?

**Comment by lintaocui** [comment]
@liu-shiyuan thank you for reporting the issue. Those fields are not exposed in Java SDK yet. You can still get it through 
`adsInsightsObj.getRawResponseAsJsonObject().get("gender") `
