### ISSUE TITLE
Support for requesting access to pages/ad accounts

### ISSUE THREAD

**Issue by nicolasdalsass** [facebook/facebook-java-ads-sdk#72]
Hi,
If I'm not mistaken, right now there is no support in the sdk to request access to pages or ad accounts ?
Is that right ? If yes, is it a planned feature ?

Thanks,
Nicolas

**Comment by sang-d** [comment]
I think it can access through ad hoc request:

`Map<String, Object> params = new HashMap<String, Object>();
            params.put("fields",
                    "id,accounts{id,name,picture,page_backed_instagram_accounts}");
            APIResponse res = new APIRequest<APINode>(context, "", "me", "GET").execute(params);`

**Comment by nicolasdalsass** [comment]
Indeed :) I was thinking more the action of requesting access, so in the end I got :

```
val params = new util.HashMap[String, AnyRef]()
    params.put("page_id", pageId)
    params.put("access_type","AGENCY")
    params.put("access_token",token)
    params.put("permitted_roles","['ADVERTISER','INSIGHTS_ANALYST']")

    val json = parse(new APIRequest[APINode](context, businessId, "/pages", "POST")
      .execute(params)
```

But yeah, ad hoc query was the way to go :)

Thanks
