### ISSUE TITLE
Business class does not support "/pages"

### ISSUE THREAD

**Issue by rickyching** [facebook/facebook-java-ads-sdk#74]
Currently Business class supports "/client_pages", "/assigned_pages" and "/owned_pages", but not "/pages".

**Comment by nicolasdalsass** [comment]
From my experience (i'm not working at FB), this is "by design", since even the business manager FB app does two http calls when you get to the "pages" tab on it : one for owned_pages, and one for client_pages. So you're pretty much left with doing the two calls too.

**Comment by cloudxu** [comment]
nicolasdalsass is correct. Hope that solves your problem @rickyching. We will get you posted when changes of pages API happens.
