### ISSUE TITLE
Not able to create Ad account using Business Manager

### ISSUE THREAD

**Issue by anthammas** [facebook/facebook-java-ads-sdk#76]
Hi. I am not able to create an Ad Account using the 'Business' class. My code below

`Business business = new Business(707942606053966L, context);
			AdAccount adAccount = business.createAdAccount().setName("AD_ACCOUNT_1").setCurrency("INR")
					.setTimezoneId(1L).setEndAdvertiser("NONE").setInvoice(true).setIo(false).setPoNumber("1")
					.execute();`

I am getting the following exception

`{"error":{"message":"(#270) Development access is not allowed to access business API post:Business\/adaccount.","type":"OAuthException","code":270,"fbtrace_id":"BYeRqnSnzQ7"}}`

Could you please help me out

**Comment by JiamingFB** [comment]
Hi @anthammas,

Looks like you don't have the required permissions.
Please refer [tiered access](https://developers.facebook.com/docs/marketing-api/access) in Facebook Marketing API.

Development tier is for early-stage apps to test accessing APIs. In general, you need to have enough numbers of successful API calls and low enough error rate to be eligible for basic tier promotion.
