### ISSUE TITLE
I'm using APIRequest with Business object.

### ISSUE THREAD

**Issue by pillowwork** [facebook/facebook-java-ads-sdk#78]
I found something strange.

So I want to ask you a question, can I write you here?

I use facebook java SDK in JAR.

I coded with APIRequest and Business object.

Like this " APIRequest<Business> request = new APIRequest<Business>(context, "me", "/businesses", "GET", Business.getParser()); request.execute(); ".

Response was " This application has no explicit mapping for /error, so you are seeing this as a fallback. 
There was an unexpected error (type=Internal Server Error, status=500).
Invalid response string: {"data":[{"name":"aaa","id":"111"},{"name":"bbb","id":"222"}],"paging":{"next":"https~~~"}} ".

So I opened the Business.java source code.

And I found " JsonObject paging = obj.get("paging").getAsJsonObject().get("cursors").getAsJsonObject(); ".

Response have no "cursors".

What should I do to use this jar file normally?

**Comment by chrisptang** [comment]
I believe this is a bug.
I've fixed on my own repository: 
https://github.com/chrisptang/facebook-java-ads-sdk/blob/master/src/main/java/com/facebook/ads/sdk/Business.java
https://github.com/chrisptang/facebook-java-ads-sdk/blob/master/src/main/java/com/facebook/ads/sdk/APINodeList.java

Here are the main changes:

APINodeList.java:

~~~
    @Deprecated
    public void setPaging(String before, String after) {
        this.before = before;
        this.after = after;
    }

    public void setPaging(JsonObject paging) {
        if (paging != null) {
            if (paging.has("cursors") && paging.get("cursors").isJsonObject()) {
                paging = paging.get("cursors").getAsJsonObject();
            }
            this.before = paging.has("before") ? paging.get("before").getAsString() : null;
            this.after = paging.has("after") ? paging.get("after").getAsString() : null;
        }
    }
~~~

Business.java and any other subclasses of APINodeList.java:

~~~
if (obj.has("paging")) {
    JsonObject paging = obj.get("paging").getAsJsonObject();
    businesss.setPaging(paging);
}
~~~

**Comment by pillowwork** [comment]
chrisptang, Thank you for your fix.

When will your changes be formally deployed to java sdk?

**Comment by chrisptang** [comment]
Actually the previous changes are already included in this compiled jar:
~~~
https://github.com/chrisptang/facebook-java-ads-sdk/blob/master/target/facebook-java-ads-sdk-0.4.0.5.jar
~~~
I have no plan to merge my codes into the original one actually. Instead, you can fix any bug you find by forking this repository as you own.
This SDK is buggy and I believe supports from Facebook team is very limited.

**Comment by pillowwork** [comment]
I have to look for other ways or wait for Facebook team to work.

Thanks, chrisptang.
