### ISSUE TITLE
Invalid search-endpoint 

### ISSUE THREAD

**Issue by tituskeuler** [facebook/facebook-java-ads-sdk#80]
I think there is an error with that searching endpoint. Using /targetingsearch leads to error message:
```
   "error": {
      "message": "Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api",
      "type": "GraphMethodException",
      "code": 100,
      "fbtrace_id": "xxxxxxxxx"
   }
}
```

If fixed it in pull request #79

**Comment by JiamingFB** [comment]
Hi @tituskeuler ,

I think it's token permission issue. Can you try the same API call https://developers.facebook.com/tools/explorer ?
