### ISSUE TITLE
Ads insights result doesn't have option to get data at breakdown fields

### ISSUE THREAD

**Issue by dirisala-gopal** [facebook/facebook-java-ads-sdk#82]
I can set the breakdown field in ads insights. Once the result is available. But, there is no way to get the data at break down fields. 

public List<AdsInsights> getAdAccountInsights(String adAccountId) {
    List<AdsInsights> result = new ArrayList<AdsInsights>();
    try {
      List<AdsInsights.EnumBreakdowns> breakdowns = new ArrayList<AdsInsights.EnumBreakdowns>();
      breakdowns
        .add(AdsInsights.EnumBreakdowns.VALUE_HOURLY_STATS_AGGREGATED_BY_ADVERTISER_TIME_ZONE);
      AdAccount account = new AdAccount(adAccountId, context);
      APINodeList<AdsInsights> adsInsights =
        account.getInsights().setDatePreset(AdsInsights.EnumDatePreset.VALUE_TODAY)
          .setLevel(AdsInsights.EnumLevel.VALUE_CAMPAIGN).setBreakdowns(breakdowns)
          .requestAllFields().execute();
      while (adsInsights != null) {
        result.addAll(adsInsights);
        adsInsights = adsInsights.nextPage();
      }
    } catch (APIException e) {
      logger.error("Api call error: ", e);
    }
    logger.debug("ads insights = {}", result);
    return result;
  }

adsInsight object doesn't have option to get data at "VALUE_HOURLY_STATS_AGGREGATED_BY_ADVERTISER_TIME_ZONE"

**Comment by bdiesenhaus** [comment]
This is big issue as API version 2.7 is being deprecated on 4/25/17.  We can't upgrade to the new SDK (0.4.0) which supports 2.8 until this is fixed. Can this be made a priority?

**Comment by JiamingFB** [comment]
We have verified the issue and we'll fix it soon.

**Comment by JiamingFB** [comment]
This should be fixed in latest release
