### ISSUE TITLE
You are calling a deprecated version of the Ads API

### ISSUE THREAD

**Issue by akohout** [facebook/facebook-java-ads-sdk#83]
I downloaded the latest available release from the releases page here at Github and get the following exception:

```
com.facebook.ads.sdk.APIException$FailedRequestException: {"error":{"message":"(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v2.8.","type":"OAuthException","code":2635,"fbtrace_id":"A2E22+VHIuy"}}
03-27 08:25:45.979 16611-17481/de.alexanderkohout.facebooklocalbusinessteacher W/System.err:     at com.facebook.ads.sdk.APIRequest.readResponse(APIRequest.java:223)
03-27 08:25:45.979 16611-17481/de.alexanderkohout.facebooklocalbusinessteacher W/System.err:     at com.facebook.ads.sdk.APIRequest.access$100(APIRequest.java:44)
03-27 08:25:45.979 16611-17481/de.alexanderkohout.facebooklocalbusinessteacher W/System.err:     at com.facebook.ads.sdk.APIRequest$DefaultRequestExecutor.sendPost(APIRequest.java:397)
03-27 08:25:45.979 16611-17481/de.alexanderkohout.facebooklocalbusinessteacher W/System.err:     at com.facebook.ads.sdk.APIRequest$DefaultRequestExecutor.execute(APIRequest.java:323)
03-27 08:25:45.979 16611-17481/de.alexanderkohout.facebooklocalbusinessteacher W/System.err:     at com.facebook.ads.sdk.APIRequest.executeInternal(APIRequest.java:157)
03-27 08:25:45.979 16611-17481/de.alexanderkohout.facebooklocalbusinessteacher W/System.err:     at com.facebook.ads.sdk.AdAccount$APIRequestCreateCampaign.execute(AdAccount.java:6914)
03-27 08:25:45.979 16611-17481/de.alexanderkohout.facebooklocalbusinessteacher W/System.err:     at com.facebook.ads.sdk.AdAccount$APIRequestCreateCampaign.execute(AdAccount.java:6909)
```

**Comment by akohout** [comment]
It works with the 0.4.0 release. Maybe you should tag the 0.4.0 release so that it is available in the releases section.

**Comment by headyrules** [comment]
I get this issue with 0.4.0 as well

**Comment by headyrules** [comment]
I fixed the problem by changing the Version of the API in Class APIConfig and recompiling the jar, took me a while to figure that out ;)
Save yourself some time: https://ufile.io/nguow

**Comment by MasterDDT** [comment]
I'm seeing this now with v2.9

>scala> account.createCustomAudience().setSubtype(CustomAudience.EnumSubtype.VALUE_CUSTOM).setName(s"miteshp_test_${Platform.currentTime}").setDescription("mitesh some descrip here").execute()
com.facebook.ads.sdk.APIException$FailedRequestException: {"error":{"message":"(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v2.9.","type":"OAuthException","code":2635,"fbtrace_id":"H8iPjKcSo\/1"}}

**Comment by headyrules** [comment]
Have you checked the URL you are requesting?

**Comment by MasterDDT** [comment]
It looks like 2.8 is hard-coded in master. I changed to using the `APIContext(str, str, "v2.9", str, str)` constructor and that seems to work now.

**Comment by headyrules** [comment]
Alternatively you can Change it in APIConfig which might be a more "Clean" way. I guess you have to do so anytime they update the API as long as this is in beta.
