### ISSUE TITLE
Instagram Ad Comments

### ISSUE THREAD

**Issue by robsoncassol** [facebook/facebook-java-ads-sdk#84]
Hi all, I want consume this endpoint "https://graph.facebook.com/<API_VERSION>/<EFFECTIVE_INSTAGRAM_STORY_ID>/comments" , you can find here https://developers.facebook.com/docs/marketing-api/guides/instagramads/ad_creative/v2.8 , but this SDK not implement any method, can I do this ? is this SDK the right place to do ?

**Comment by cloudxu** [comment]
@robsoncassol, thanks for the feedback, but instagram story is not a part of Ads API SDK at this point.
