### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by hcura** [facebook/facebook-java-ads-sdk#87]
What happened with versioning? What's supposed to be the current one?

A bit confusing because you moved from 0.4.1 to 2.9.0 - which is the API version, not the library. Is this intended or a mistake?

**Comment by JiamingFB** [comment]
Hi @hcura ,

Thanks for bring this up.

We start using API_MAJOR.API_MINOR.RELEASE as the SDK version code. This might cause some confusion right now, but it can reduce confusion about the API version vs SDK version later on.
