### ISSUE TITLE
Add maven repository support

### ISSUE THREAD

**Issue by gogl92** [facebook/facebook-java-ads-sdk#88]
This project could be used easily using Maven and/or Gradle version management.
Using jars files increases the deployment work

**Comment by rockneverdies55** [comment]
It's already in maven standard repo. All you need to do is to add the following to your project pom:

```xml
        <dependency>
            <groupId>com.facebook.ads.sdk</groupId>
            <artifactId>facebook-java-ads-sdk</artifactId>
            <version>{mvn-facebook-ads-sdk-vesion}</version>
        </dependency>
```
Replace `{mvn-facebook-ads-sdk-vesion}` with the version you want to use e.g. `2.9.0`.

**Comment by guxufb** [comment]
Thanks @rockneverdies55
