### ISSUE TITLE
Error parameter page_id required when fetching an AdAccount 

### ISSUE THREAD

**Issue by SaulG** [facebook/facebook-java-ads-sdk#89]
Hi, I would like to fetch the data for an Ad Account, but since versions 0.4.1 and 2.9.0 I got the following error: 

 `{"error":{"message":"(#100) For field 'show_checkout_experience': The parameter page_id is required","type":"OAuthException","code":100,"fbtrace_id":"xxxxxxx"}}`

I know that I need to add the **page_id** as parameter, but I don't need the field  **show_checkout_experience**. 

What I need mainly is the **currency** of the AdAccount, so is there a way to ask for it without the field **show_checkout_experience**?

Thanks for advanced.

**Comment by daphyFB** [comment]
Thanks for reporting Ads API SDK issues.
Have you tried providing the page_id in the API call already? If you haven't, please try it without providing the show_check_experience too. If you have, the the call failed, could you please share the fbtrace_id for us to debug? Thanks!

**Comment by SaulG** [comment]
Thanks for the response, I did provide the **page_id** and just asking for the **currency** field, but I received an empty value. 

So I did run it again with the same error as above and now I have the fbtrace_id which is GanCnnJCXwl.

**Comment by SaulG** [comment]
I solved my problem.

Instead of calling fetch, I did just call get and requestCurrencyField then execute the request.

**Comment by deviant-studio** [comment]
this is still an issue! why we just can't `fetch` and retrieve all available fields?
