### ISSUE TITLE
How do we access the batch request's responses?

### ISSUE THREAD

**Issue by pshussain** [facebook/facebook-java-ads-sdk#9]

**Comment by faisalbasra** [comment]
responses.get(0)
responses.get(1)
responses.get(2)

like that.

**Comment by pshussain** [comment]
@faisalbasra  If we have dependency in the request?

**Comment by pshussain** [comment]
List<APIResponse> responses = batch.execute();
  // responses contains the result of each API call in order. However, if the API calls have dependency, then some result could be null.

**Comment by faisalbasra** [comment]
Yes, you can check what is successful and what is failed. If you get campaignId, AdsetId, AdId then most probably your flow is successful.

**Comment by guxuoss** [comment]
close this as it seems to be resolved already.
