### ISSUE TITLE
v2.9.0 not in maven

### ISSUE THREAD

**Issue by 0cd** [facebook/facebook-java-ads-sdk#93]
When can we expect ver 2.9.0 in maven repo? Only 0.4.0 is present

https://mvnrepository.com/artifact/com.facebook.ads.sdk/facebook-java-ads-sdk

**Comment by databanana** [comment]
@JiamingFB, looks like you are the developer listed in the POM, any update on this?

**Comment by cloudxu** [comment]
Yes, we are working on push it to Maven

**Comment by xiaotchen** [comment]
I've just pushed it to Maven as 2.9.0 (we bump up the version to align with the API version because java sdk is not in beta mode anymore). It should be available shortly :)
