### ISSUE TITLE
Incorrect type use for TargetingGeoLocationCity.radius

### ISSUE THREAD

**Issue by nicolasdalsass** [facebook/facebook-java-ads-sdk#94]
Hi,

For geolocation targeting, TargetingGeoLocationCity.radius is typed Long, but should really be Float/Double to accomodate non integer values. 

Also, it seems like Double is the goto type for radius and latitude/longitude in other classes, which I find a bit wasteful considering that those values are naturally bounded (assuming FB doesn't expand in space ;) ) !

Thanks,
Nicolas

**Comment by guxufb** [comment]
Thanks for the feedback!  

For TargetingGeoLocationCity.radius, API only allows integers and SDK follows the specification of APIs.  Questions about API design may not be addressed here.

Our SDK is automatically generated based on the specification of API.  I agree that if we use other types to store lat/long in SDK we can save some memory on the client side.  But the saving is too small to be able to justify the development/maintenance cost of special handling in our auto-gen framework. So far, we do not have plans to do it.

**Comment by nicolasdalsass** [comment]
Thanks for the precisions, I got confused between the differing radius specs !
