### ISSUE TITLE
Usage of TargetingGeoLocationMarket.mMarketType ?

### ISSUE THREAD

**Issue by nicolasdalsass** [facebook/facebook-java-ads-sdk#95]
Hi,

What is the usage, if any, for TargetingGeoLocationMarket.mMarketType ? I don't see it in use neither in the Graph API response nor in the API calls made by the Ads Manager.

Thanks,
Nicolas

**Comment by guxufb** [comment]
It is an readonly field.  It can be something like "geo_market" or "city".  You can find some examples with the targeting search API.  https://graph.facebook.com/v2.9/search?type=adgeolocation&q=Los angeles&access_token=...
