### ISSUE TITLE
Javadoc typo in codegen framework

### ISSUE THREAD

**Issue by isitinschi** [facebook/facebook-java-ads-sdk#97]
Every javadoc starts with "This class is auto-genereated". Should be "generated"

As example, see "AdAccountTargetingUnified" class

Also generated classes have a lot of unused imports. Don't know if you'd like to fix it

**Comment by cloudxu** [comment]
Thank you for pointing it out. We will fix the typo in the next release. For the unused imports, it may be a bit tricky to do since the code is generated.
